services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "8050:8050"
    environment:
      API_URL: http://backend:8080/predict
    depends_on:
      - backend